---
title: "P_EDA_Metro"
author: "Alyson Givre"
date: "4/28/2021"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Metropolitan Level Data

### Descriptive Statistics
```{r state, include=FALSE}
source('../process-data.R')

fbi <- get_metro_data('../data/')

s <- sd(fbi$PropertyCrimeRate)
v <- s**2
```

```{r, echo=FALSE}
sprintf('Mean: %.2f', mean(fbi$PropertyCrimeRate))
sprintf('Median: %.2f', median(fbi$PropertyCrimeRate))
sprintf('Standard deviation: %.2f', s)
sprintf('Variance: %.2f', v)
sprintf('Range: (%.2f, %.2f)', min(fbi$PropertyCrimeRate), max(fbi$PropertyCrimeRate))
```


### Histogram of Crime Rate
```{r hist, echo=FALSE}

ggplot(data=fbi, aes(x=PropertyCrimeRate)) +
  geom_histogram(aes(y = ..density..,fill=..count..,alpha=0.2),bins=32, closed='left') +
  geom_density(fill='red',alpha=0.2) +
  xlab('Crime Rate (per 100,000)') +
  ylab('Density')
```


### QQ Plot
```{r qq, echo=FALSE}

ggplot(fbi, aes(sample=PropertyCrimeRate)) +
  stat_qq() +
  stat_qq_line()
```

### Population versus Number of Crime Incidents
```{r vc, echo=FALSE}

fbi$LegalizedText <- ifelse(fbi$Legalized, 'Legal', 'Illegal')

ggplot(fbi, aes(x=Population, y=PropertyCrimeRate)) + 
  geom_point() +
  geom_smooth(method=lm) +
  facet_grid(. ~ LegalizedText)
```

### Population versus Crime Rate
```{r pop, echo=FALSE}
ggplot(fbi, aes(x=Population, y=PropertyCrimeRate)) + 
  geom_point() +
  geom_smooth(method=lm) +
  facet_grid(. ~ LegalizedText)
```